from agimus_sot.srdf_parser import parse_srdf_string

srdf="""<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from plank_of_wood_srdf.xacro       | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="plank_of_wood1" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <handle name="handle1" clearance="0.08">
    <position> -0.06 0 0  0.707106781187 -0.707106781187 0 0 </position>
    <link name="base_link"/>
  </handle>
  <handle name="handle2" clearance="0.08">
    <position> 0.06 0 0  0 0 -0.707106781187 0.707106781187 </position>
    <link name="base_link"/>
  </handle>

  <contact name="bottom_surface">
    <link name="base_link"/>
    <point>
      +0.105 +0.02 -0.071
      +0.105 -0.02 -0.071
      -0.105 -0.02 -0.071
      -0.105 +0.02 -0.071
    </point>
    <shape>
      4 0 1 2 3
    </shape>
  </contact>
  <contact name="top_surface">
    <link name="base_link"/>
    <point>
      +0.1015 +0.022 0.058
      +0.1015 -0.022 0.058
      -0.1015 -0.022 0.058
      -0.1015 +0.022 0.058
    </point>
    <shape>
      4 3 2 1 0
    </shape>
  </contact>
</robot>
"""

content = parse_srdf_string (srdf)
